export enum PRODUCT_STATUS {
  NONE = "all",
}

export enum ORDER_STATUS {
  NONE = "all",
  PENDING = "PENDING",
  SHIPPED = "SHIPPED",
  OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY",
  DELIVERED = "DELIVERED",
  CANCELED = "CANCELED",
  FAILED_DELIVERY = "FAILED_DELIVERY",
}

export enum EMPLOYEE_APPROVAL_STATUS {
  PENDING = "pending",
  APPROVED = "approved",
  REJECTED = "rejected",
}

export enum CLIENT_APPROVAL_STATUS {
  NONE = "all",
}

export enum EMPLOYEE_APPROVAL_STATUS {
  NONE = "all",
}

export enum TABLE_ROW_TYPE {
  PRODUCT_NAME = "PRODUCT_NAME",
  PRODUCT_DESCRIPTION = "PRODUCT_DESCRIPTION",
  PRICE = "PRICE",
  STOCK = "STOCK",
  CATEGORY = "CATEGORY",
  SUB_CATEGORY = "SUB_CATEGORY",
  AGENT_NAME = "AGENT_NAME",
  STATUS = "STATUS",
  NAME = "NAME",
  CREATED_AT_DATE = "CREATED_AT_DATE",
  UPDATED_AT_DATE = "UPDATED_AT_DATE",
  ORDER_NAME = "ORDER_NAME",
  ORDER_PRODUCT_NAME = "ORDER_PRODUCT_NAME",
  ORDER_PRICE = "ORDER_PRICE",
  ORDER_STATUS = "ORDER_STATUS",
  ORDERED_ITEM_COUNT = "ORDERED_ITEM_COUNT",
}

export enum UPLOAD_FORMATS {
  IMAGE = "imageUploader",
  PDF = "pdfUploader",
  VIDEO = "videoUploader",
}
