export enum PRODUCT_STATUS {
  NONE = "all",
}

export enum EMPLOYEE_APPROVAL_STATUS {
  PENDING = "pending",
  APPROVED = "approved",
  REJECTED = "rejected",
}

export enum CLIENT_APPROVAL_STATUS {
  NONE = "all",
}

export enum EMPLOYEE_APPROVAL_STATUS {
  NONE = "all",
}

export enum TABLE_ROW_TYPE {
  PRODUCT_NAME = "PRODUCT_NAME",
  PRODUCT_DESCRIPTION = "PRODUCT_DESCRIPTION",
  PRICE = "PRICE",
  STOCK = "STOCK",
  CATEGORY = "CATEGORY",
  SUB_CATEGORY = "SUB_CATEGORY",
  APPROVAL_STATUS = "APPROVAL_STATUS",
  AGENT_NAME = "AGENT_NAME",
  STATUS = "STATUS",
  TEAMS = "TEAMS",
  ROLE = "ROLE",
  EMPLOYEE_ID = "EMPLOYEE_ID",
  NAME = "NAME",
  APARTMENT_LIST = "APARTMENT_LIST",
  SUSPENDED = "SUSPENDED",
}

export enum UPLOAD_FORMATS {
  IMAGE = "imageUploader",
  PDF = "pdfUploader",
  VIDEO = "videoUploader",
}
