export const VERIFIED_EMAIL_KEY = "verifiedEmail";

export const RtkqTagEnum = {
  ERROR: "ERROR",
  AUTH: "AUTH",
  PRODUCTS: "PRODUCTS",
  USERS: "USERS",
  EMPLOYEES: "EMPLOYEES",
  CLIENTS: "CLIENTS",
  ADMINS: "ADMINS",

  COLORS: "COLORS",
  SIZES: "SIZES",
  TYPES: "TYPES",
  CATEGORIES: "CATEGORIES",
  SUBCATEGORIES: "SUBCATEGORIES",
};
